// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(localgpt_mobileFFI)
import localgpt_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_localgpt_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_localgpt_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureLocalgptMobileInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Thread-safe client for interacting with LocalGPT from mobile apps.
 *
 * Create one instance at app launch with `LocalGPTClient::new()` and keep
 * it alive for the lifetime of the app. All methods are safe to call from
 * any thread.
 */
public protocol LocalGptClientProtocol: AnyObject, Sendable {
    
    /**
     * Send a chat message and return the full response.
     */
    func chat(message: String) throws  -> String
    
    /**
     * Clear session history.
     */
    func clearSession() 
    
    /**
     * Compact the current session to free context space.
     */
    func compactSession() throws 
    
    /**
     * Configure an API key for a provider.
     */
    func configureProvider(provider: String, apiKey: String) throws 
    
    /**
     * Get the HEARTBEAT.md content.
     */
    func getHeartbeat() throws  -> String
    
    /**
     * Get the MEMORY.md content.
     */
    func getMemory() throws  -> String
    
    /**
     * Get the current model name.
     */
    func getModel()  -> String
    
    /**
     * Get the POLICY.md content (security policy / standing instructions).
     *
     * Falls back to the legacy `LocalGPT.md` when `POLICY.md` does not
     * exist yet, so workspaces created before the rename keep working.
     */
    func getPolicy() throws  -> String
    
    /**
     * Get the SOUL.md content (persona/tone guidance).
     */
    func getSoul() throws  -> String
    
    /**
     * Read an arbitrary workspace file by name.
     *
     * Only the known editable files (MEMORY.md, SOUL.md, HEARTBEAT.md,
     * POLICY.md — plus the legacy LocalGPT.md) are allowed. Returns
     * `MobileError::Memory` for unknown file names to prevent
     * path-traversal.
     */
    func getWorkspaceFile(filename: String) throws  -> String
    
    /**
     * Check if this is a brand new workspace (first run).
     * Mobile apps can use this to display a custom welcome message.
     */
    func isBrandNew()  -> Bool
    
    /**
     * Check whether a workspace file is security-sensitive.
     *
     * Security-sensitive files (like POLICY.md) affect the agent's
     * security policy and require user confirmation before editing.
     * The mobile UI should display a warning dialog before allowing
     * edits to these files.
     */
    func isWorkspaceFileSecuritySensitive(filename: String)  -> Bool
    
    /**
     * List available provider names.
     */
    func listProviders()  -> [String]
    
    /**
     * List the editable workspace files with their current content.
     *
     * Returns `WorkspaceFile` entries for MEMORY.md, SOUL.md,
     * HEARTBEAT.md, and POLICY.md. Files that do not exist yet are
     * returned with an empty `content` string. Security-sensitive files
     * (like POLICY.md) are flagged with `is_security_sensitive = true`.
     * For POLICY.md, the content falls back to the legacy `LocalGPT.md`
     * when the renamed file does not exist yet.
     */
    func listWorkspaceFiles()  -> [WorkspaceFile]
    
    /**
     * Read a memory file by name (e.g. "MEMORY.md").
     */
    func memoryGet(filename: String) throws  -> String
    
    /**
     * Search memory files.
     */
    func memorySearch(query: String, maxResults: UInt32) throws  -> [SearchResult]
    
    /**
     * Start a fresh session.
     */
    func newSession() throws 
    
    /**
     * Get session status.
     */
    func sessionStatus()  -> SessionStatus
    
    /**
     * Write new HEARTBEAT.md content.
     */
    func setHeartbeat(content: String) throws 
    
    /**
     * Write new MEMORY.md content.
     */
    func setMemory(content: String) throws 
    
    /**
     * Switch to a different model.
     */
    func setModel(model: String) throws 
    
    /**
     * Write new POLICY.md content (security policy / standing instructions).
     *
     * This is a plain file write — the policy is loaded and sanitized at
     * the next session start. Editing is only allowed through explicit
     * user action (never by the agent).
     */
    func setPolicy(content: String) throws 
    
    /**
     * Write new SOUL.md content.
     */
    func setSoul(content: String) throws 
    
    /**
     * Write an arbitrary workspace file by name.
     *
     * Only the known editable files (MEMORY.md, SOUL.md, HEARTBEAT.md,
     * POLICY.md — plus the legacy LocalGPT.md) are allowed. The caller
     * (mobile UI) must confirm security-sensitive file edits before
     * calling this method. Writing via the legacy name stores to
     * POLICY.md.
     */
    func setWorkspaceFile(filename: String, content: String) throws 
    
}
/**
 * Thread-safe client for interacting with LocalGPT from mobile apps.
 *
 * Create one instance at app launch with `LocalGPTClient::new()` and keep
 * it alive for the lifetime of the app. All methods are safe to call from
 * any thread.
 */
open class LocalGptClient: LocalGptClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_localgpt_mobile_fn_clone_localgptclient(self.handle, $0) }
    }
    /**
     * Create a new client rooted at the given directory.
     *
     * `data_dir` should be the app's document or library directory
     * (e.g. `NSDocumentDirectory` on iOS, `Context.filesDir` on Android).
     */
public convenience init(dataDir: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_constructor_localgptclient_new(
        FfiConverterString.lower(dataDir),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_localgpt_mobile_fn_free_localgptclient(handle, $0) }
    }

    

    
    /**
     * Send a chat message and return the full response.
     */
open func chat(message: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_chat(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(message),$0
    )
})
}
    
    /**
     * Clear session history.
     */
open func clearSession()  {try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_clear_session(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Compact the current session to free context space.
     */
open func compactSession()throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_compact_session(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Configure an API key for a provider.
     */
open func configureProvider(provider: String, apiKey: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_configure_provider(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(provider),
        FfiConverterString.lower(apiKey),$0
    )
}
}
    
    /**
     * Get the HEARTBEAT.md content.
     */
open func getHeartbeat()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_heartbeat(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get the MEMORY.md content.
     */
open func getMemory()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_memory(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get the current model name.
     */
open func getModel() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_model(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get the POLICY.md content (security policy / standing instructions).
     *
     * Falls back to the legacy `LocalGPT.md` when `POLICY.md` does not
     * exist yet, so workspaces created before the rename keep working.
     */
open func getPolicy()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_policy(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get the SOUL.md content (persona/tone guidance).
     */
open func getSoul()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_soul(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Read an arbitrary workspace file by name.
     *
     * Only the known editable files (MEMORY.md, SOUL.md, HEARTBEAT.md,
     * POLICY.md — plus the legacy LocalGPT.md) are allowed. Returns
     * `MobileError::Memory` for unknown file names to prevent
     * path-traversal.
     */
open func getWorkspaceFile(filename: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_get_workspace_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(filename),$0
    )
})
}
    
    /**
     * Check if this is a brand new workspace (first run).
     * Mobile apps can use this to display a custom welcome message.
     */
open func isBrandNew() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_is_brand_new(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Check whether a workspace file is security-sensitive.
     *
     * Security-sensitive files (like POLICY.md) affect the agent's
     * security policy and require user confirmation before editing.
     * The mobile UI should display a warning dialog before allowing
     * edits to these files.
     */
open func isWorkspaceFileSecuritySensitive(filename: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_is_workspace_file_security_sensitive(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(filename),$0
    )
})
}
    
    /**
     * List available provider names.
     */
open func listProviders() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_list_providers(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * List the editable workspace files with their current content.
     *
     * Returns `WorkspaceFile` entries for MEMORY.md, SOUL.md,
     * HEARTBEAT.md, and POLICY.md. Files that do not exist yet are
     * returned with an empty `content` string. Security-sensitive files
     * (like POLICY.md) are flagged with `is_security_sensitive = true`.
     * For POLICY.md, the content falls back to the legacy `LocalGPT.md`
     * when the renamed file does not exist yet.
     */
open func listWorkspaceFiles() -> [WorkspaceFile]  {
    return try!  FfiConverterSequenceTypeWorkspaceFile.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_list_workspace_files(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Read a memory file by name (e.g. "MEMORY.md").
     */
open func memoryGet(filename: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_memory_get(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(filename),$0
    )
})
}
    
    /**
     * Search memory files.
     */
open func memorySearch(query: String, maxResults: UInt32)throws  -> [SearchResult]  {
    return try  FfiConverterSequenceTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_memory_search(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
    
    /**
     * Start a fresh session.
     */
open func newSession()throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_new_session(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Get session status.
     */
open func sessionStatus() -> SessionStatus  {
    return try!  FfiConverterTypeSessionStatus_lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_method_localgptclient_session_status(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Write new HEARTBEAT.md content.
     */
open func setHeartbeat(content: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_heartbeat(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(content),$0
    )
}
}
    
    /**
     * Write new MEMORY.md content.
     */
open func setMemory(content: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_memory(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(content),$0
    )
}
}
    
    /**
     * Switch to a different model.
     */
open func setModel(model: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_model(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(model),$0
    )
}
}
    
    /**
     * Write new POLICY.md content (security policy / standing instructions).
     *
     * This is a plain file write — the policy is loaded and sanitized at
     * the next session start. Editing is only allowed through explicit
     * user action (never by the agent).
     */
open func setPolicy(content: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_policy(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(content),$0
    )
}
}
    
    /**
     * Write new SOUL.md content.
     */
open func setSoul(content: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_soul(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(content),$0
    )
}
}
    
    /**
     * Write an arbitrary workspace file by name.
     *
     * Only the known editable files (MEMORY.md, SOUL.md, HEARTBEAT.md,
     * POLICY.md — plus the legacy LocalGPT.md) are allowed. The caller
     * (mobile UI) must confirm security-sensitive file edits before
     * calling this method. Writing via the legacy name stores to
     * POLICY.md.
     */
open func setWorkspaceFile(filename: String, content: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_localgpt_mobile_fn_method_localgptclient_set_workspace_file(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(filename),
        FfiConverterString.lower(content),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocalGPTClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = LocalGptClient

    public static func lift(_ handle: UInt64) throws -> LocalGptClient {
        return LocalGptClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: LocalGptClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocalGptClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: LocalGptClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalGPTClient_lift(_ handle: UInt64) throws -> LocalGptClient {
    return try FfiConverterTypeLocalGPTClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalGPTClient_lower(_ value: LocalGptClient) -> UInt64 {
    return FfiConverterTypeLocalGPTClient.lower(value)
}




/**
 * A search result returned from memory search.
 */
public struct SearchResult: Equatable, Hashable {
    public var file: String
    public var content: String
    public var score: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(file: String, content: String, score: Double) {
        self.file = file
        self.content = content
        self.score = score
    }

    

    
}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                file: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.file, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


/**
 * Session status information.
 */
public struct SessionStatus: Equatable, Hashable {
    public var model: String
    public var tokensUsed: UInt64
    public var tokensAvailable: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(model: String, tokensUsed: UInt64, tokensAvailable: UInt64) {
        self.model = model
        self.tokensUsed = tokensUsed
        self.tokensAvailable = tokensAvailable
    }

    

    
}

#if compiler(>=6)
extension SessionStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionStatus {
        return
            try SessionStatus(
                model: FfiConverterString.read(from: &buf), 
                tokensUsed: FfiConverterUInt64.read(from: &buf), 
                tokensAvailable: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SessionStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.model, into: &buf)
        FfiConverterUInt64.write(value.tokensUsed, into: &buf)
        FfiConverterUInt64.write(value.tokensAvailable, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStatus_lift(_ buf: RustBuffer) throws -> SessionStatus {
    return try FfiConverterTypeSessionStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStatus_lower(_ value: SessionStatus) -> RustBuffer {
    return FfiConverterTypeSessionStatus.lower(value)
}


/**
 * A workspace file entry for the editor.
 */
public struct WorkspaceFile: Equatable, Hashable {
    /**
     * File name (e.g. "MEMORY.md").
     */
    public var name: String
    /**
     * File content, or empty string if the file does not yet exist.
     */
    public var content: String
    /**
     * Whether this file is security-sensitive and requires confirmation before editing.
     */
    public var isSecuritySensitive: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * File name (e.g. "MEMORY.md").
         */name: String, 
        /**
         * File content, or empty string if the file does not yet exist.
         */content: String, 
        /**
         * Whether this file is security-sensitive and requires confirmation before editing.
         */isSecuritySensitive: Bool) {
        self.name = name
        self.content = content
        self.isSecuritySensitive = isSecuritySensitive
    }

    

    
}

#if compiler(>=6)
extension WorkspaceFile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceFile: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceFile {
        return
            try WorkspaceFile(
                name: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                isSecuritySensitive: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceFile, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterBool.write(value.isSecuritySensitive, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceFile_lift(_ buf: RustBuffer) throws -> WorkspaceFile {
    return try FfiConverterTypeWorkspaceFile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceFile_lower(_ value: WorkspaceFile) -> RustBuffer {
    return FfiConverterTypeWorkspaceFile.lower(value)
}


public enum MobileError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Init(String
    )
    case Chat(String
    )
    case Memory(String
    )
    case Config(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension MobileError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileError: FfiConverterRustBuffer {
    typealias SwiftType = MobileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Init(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Chat(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .Memory(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .Config(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Init(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Chat(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Memory(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Config(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileError_lift(_ buf: RustBuffer) throws -> MobileError {
    return try FfiConverterTypeMobileError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileError_lower(_ value: MobileError) -> RustBuffer {
    return FfiConverterTypeMobileError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspaceFile: FfiConverterRustBuffer {
    typealias SwiftType = [WorkspaceFile]

    public static func write(_ value: [WorkspaceFile], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspaceFile.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkspaceFile] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkspaceFile]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspaceFile.read(from: &buf))
        }
        return seq
    }
}
/**
 * Get the first-run welcome message text.
 * Mobile apps can display this when `is_brand_new()` returns true.
 */
public func getWelcomeMessage() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_localgpt_mobile_fn_func_get_welcome_message($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_localgpt_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_localgpt_mobile_checksum_func_get_welcome_message() != 36059) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_chat() != 54878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_clear_session() != 48151) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_compact_session() != 65445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_configure_provider() != 50082) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_heartbeat() != 30611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_memory() != 44993) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_model() != 10028) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_policy() != 9101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_soul() != 1522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_get_workspace_file() != 62437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_is_brand_new() != 50749) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_is_workspace_file_security_sensitive() != 36943) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_list_providers() != 61507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_list_workspace_files() != 19167) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_memory_get() != 5686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_memory_search() != 24769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_new_session() != 1913) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_session_status() != 33661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_heartbeat() != 47503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_memory() != 23855) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_model() != 47445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_policy() != 2607) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_soul() != 13659) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_method_localgptclient_set_workspace_file() != 58323) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_localgpt_mobile_checksum_constructor_localgptclient_new() != 46122) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureLocalgptMobileInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all